apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iz0b29kkg-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-2b1aef2f6a.i9ps.p3.openshiftapps.com/rhtap/rhtap-qe:83d3c96f541783f426f97c78e967112dd0cb2a74@sha256:17ab1cb2fd8b20681663b6740565a0489e988a52d6a1c4abf395679cfcd60cab
          name: container-image
